### ISSUE TITLE
Add option for batch export

### ISSUE THREAD

**Issue by RQWorldblender** [Ploaj/SSBHLib#12]
I'm grateful that I can even export the nutexb and numdlb files, but going through multiple models becomes very tiring.

I'm more concerned about the numdlb files, rather than the nutexb files, where I already used [Switch-Toolbox](https://github.com/KillzXGaming/Switch-Toolbox) to convert the majority of textures.

**Comment by Ploaj** [comment]
The model exporting, especially DAE, is not stable and should not be used for general exporting, let alone batch, at this time.
Maybe once exporting gets far enough we will add an option in the "Experimental" tab.

**Comment by RQWorldblender** [comment]
Well, that is the only other option that I have since I'm trying to avoid the use of 3DS Max if possible. But the exports that I did so far, turned out good enough for now.

**Comment by CarlosFdez** [comment]
I was tempted on implementing this, since I saw how far along you guys have come. Was wondering if it should do it as a top-level menu option or an additional context menu option on model exports though (Export with Dependencies).

Unless by batch you mean "a bunch of DAE files one after the other". In which case deeper workspace nesting would be cool but might be tricky to get right in a user friendly way.

**Comment by ScanMountGoat** [comment]
It would be very easy to implement, but we don't want to encourage using the experimental export feature more than necessary.
