### ISSUE TITLE
MatLab doesn't rebuild NUMATB 1:1 (missing BlendState padding)

### ISSUE THREAD

**Issue by ThatNintendoNerd** [Ploaj/SSBHLib#51]
Converting a .numatb file to .xml and back with no changes results in different binary data compared to the source file. Converting this new .numatb to .xml and comparing the two .xml files shows they are identical. Unsure of the specific commit where this started occurring, though MatLab compiled from source from Cross Mod's 0.14 release does not have this issue. Example files are provided below.
[matl_issue.zip](https://github.com/Ploaj/SSBHLib/files/5977408/matl_issue.zip)

**Comment by ScanMountGoat** [comment]
Some of the struct definitions changed, so there's probably some padding bytes missing somewhere.

**Comment by ThatNintendoNerd** [comment]
Further investigation into the problem reveals that it may be a problem with BlendState, as removing it allows the `.numatb` file to rebuild 1:1 between the old and new versions of MatLab. Two 32-bit values appear to be missing after Unk10, which used to be Unk11 and Unk12 respectively. ssbh_lib's [format module](https://github.com/ultimate-research/ssbh_lib/blob/master/ssbh_lib/src/formats/matl.rs#L670) doesn't account for this yet the file rebuilds properly when run under ssbh_lib_json.exe, so I'm not sure how this is done.

**Comment by ScanMountGoat** [comment]
The Rust code is almost entirely automatically generated, which is why you don't see any functions in most of the source files. The `#[ssbhwrite(pad_after = 8)]` attribute instructs the `SsbhWrite` derive macro to generate the appropriate padding code. You can run `rustup run nightly cargo rustc -- -Zunstable-options --pretty=expanded > expand.rs` if you're curious what the code looks like. Search for "SsbhWrite for MatlBlendState" to find it.

There's a corresponding struct in Nrpd that doesn't have unk11 and unk12. https://github.com/ultimate-research/ssbh_lib/blob/476b455541c2af13ded42647e15964048c29564c/ssbh_lib/src/formats/nrpd.rs#L122-L134. 

It should be a simple fix on the C# side to just write 8 bytes of zeros in the export method for MatlBlendState. The C# exporter is really messy, so it may be more involved in practice.
